C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitcparam(setupfunc)
      external setupfunc
      real(kind=8) rho
      real(kind=8) bulk
      real(kind=8) cc
      real(kind=8) zz
      common /cparam/ rho,bulk,cc,zz
      call setupfunc(rho,bulk,cc,zz)
      end


